updated aha-submod-flow-steps to latest version

diff --git a/.buildkite/aha-submod-flow-steps.yml b/.buildkite/aha-submod-flow-steps.yml
--- a/.buildkite/aha-submod-flow-steps.yml
+++ b/.buildkite/aha-submod-flow-steps.yml
@@ -1,33 +1,38 @@
+################################################################################
+# This is a copy of the online buildkite steps for the aha-submod-flow pipeline,
+# see https://buildkite.com/stanford-aha/aha-submod-flow/settings/steps
+# 
+# Last update Sep 2024
+################################################################################
 # To prevent github push events from triggering builds, set pipeline
 # github settings to "Filter builds using a conditional" with:
 #     build.pull_request.base_branch == "master"
 # (https://buildkite.com/stanford-aha/aha-submod-flow/settings/repository)
 
+env:
+  DEV_BRANCH: master
+  # DEV_BRANCH: ci-cleanup
+  AHA_REPO: https://raw.githubusercontent.com/StanfordAHA/aha
+  STEPSCRIPT: .buildkite/bin/custom-checkout.sh
+
 steps:
 - label: ":pipeline:"
   agents: { docker: true }
+  command: echo "--- DONE"
   plugins:
-      # Turn off normal/slow repo+submods checkout b/c all we need is pipeline.yml
-      - uber-workflow/run-without-clone:
-  commands:
-  - 'echo "+++ Must have (empty!) working directory"; set -x;
-     d=$$BUILDKITE_BUILD_CHECKOUT_PATH;
-     /bin/rm -rf $$d; mkdir -p $$d; ls -ld $$d; cd $$d'
-  
-  # Note, /home/buildkite-agent/bin/status-update must exist on agent machine
-  # Also see ~steveri/bin/status-update on kiwi
-  - 'echo "+++ Notify github of pending status";
-     ~/bin/status-update --force pending'
-  
-  - 'echo "--- CUSTOM CHECKOUT BEGIN"; set -x;
-     aha_clone=$$BUILDKITE_BUILD_CHECKOUT_PATH;
-     git clone https://github.com/StanfordAHA/aha $$aha_clone; cd $$aha_clone;
-
-     echo "Set BPPR_TAIL for later usage, e.g. BPPR_TAIL=canal";
-     export BPPR_TAIL=`echo "$BUILDKITE_PULL_REQUEST_REPO" | sed "s/.git\$//"` || echo fail;
-     BPPR_TAIL=`echo "$$BPPR_TAIL" | sed "s,http.*github.com/.*/,,"` || echo fail;
-       
-     echo "Trigger aha-flow pipeline";
-     buildkite-agent pipeline upload .buildkite/pr_trigger.yml;'
-  - echo "--- CUSTOM CHECKOUT END"
-
+    # Turn off normal/slow repo+submods checkout b/c all we need is pipeline.yml
+    - uber-workflow/run-without-clone:
+      
+    # My hooks
+    - improbable-eng/metahook:
+        pre-checkout: |
+          set -x
+          echo FOO DEBUGGO
+          udev=$$AHA_REPO/$$DEV_BRANCH/$$STEPSCRIPT
+          httpcode=`curl $$udev -o custom-checkout.sh -w '%{http_code}'`
+          if ! [ "$$httpcode" == 200 ]; then
+              echo "Cannot find steps in branch '$$DEV_BRANCH'; trying master instead"
+              curl $$AHA_REPO/master/$$STEPSCRIPT -o custom-checkout.sh
+          fi
+          source custom-checkout.sh --aha-submod-flow
+          exit
