oh my aching brain

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -14,7 +14,7 @@ env:
   TAG: aha-flow-build-$BUILDKITE_BUILD_NUMBER
 
   RM_SRC1: $$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh
-  RM_SRC2: $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh
+  # RM_SRC2: $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh
 
 steps:
 
@@ -202,14 +202,15 @@ steps:
 
     - improbable-eng/metahook:
         pre-command: |
-            echo "+++ BUILDKITE_BUILD_CHECKOUT_PATH=$$BUILDKITE_BUILD_CHECKOUT_PATH (me)"  # right for this step
-            echo "+++ BUILDKITE_BUILD_CHECKOUT_PATH=$BUILDKITE_BUILD_CHECKOUT_PATH (docker step)"   # right for docker step(??)
-            echo "+++ RM_SRC1=$RM_SRC1"
-            echo "+++ RM_SRC2=$RM_SRC2"
+            # echo "+++ BUILDKITE_BUILD_CHECKOUT_PATH=$$BUILDKITE_BUILD_CHECKOUT_PATH (me)"  # right for this step
+            # echo "+++ BUILDKITE_BUILD_CHECKOUT_PATH=$BUILDKITE_BUILD_CHECKOUT_PATH (docker step)"   # right for docker step(??)
+            echo "+++ RM_SRC1=$RM_SRC1 (me)"
+            # echo "+++ RM_SRC2=$RM_SRC2 (docker step)"
             set -x
             # test -f $REGRESS_METAHOOKS || cp $$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $$COMMON
             # Must restore in case of retries
-            test -f $REGRESS_METAHOOKS || cp $$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
+            test -f $REGRESS_METAHOOKS || echo "--- OOPS missing metahooks: cp $RM_SRC1 $REGRESS_METAHOOKS"
+            test -f $REGRESS_METAHOOKS || cp $RM_SRC1 $REGRESS_METAHOOKS
             REGRESSION_STEP=0 $REGRESS_METAHOOKS --pre-command
         pre-exit:    $REGRESS_METAHOOKS --pre-exit
 
