more sophisticated retry maybe, with flock locks

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -64,9 +64,19 @@ steps:
 
         ~/bin/status-update --force pending   # Send "pending" status to github PR page
 
-        # ~Checkout and update correct aha branch and submodules~
+        # TEMPORARILY Checkout and update correct aha branch and submodules
+        # source $$bin/custom-checkout.sh --aha-flow --early-out
+
+
+
+
+
         # Checkout and update correct aha branch and *NOT* submodules
         source $$bin/custom-checkout.sh --aha-flow --early-out
+
+
+
+
 
       # Send regression test pass-fail info to github pull request page
       pre-exit: |
@@ -204,19 +214,46 @@ steps:
             # Must restore in case of retries
             if ! test -f $REGRESS_METAHOOKS; then
                 set -x
-                cd ..  # "/var/lib/buildkite-agent/builds/r8cad-docker-3/stanford-aha" maybe
-                echo I am in dir `pwd`
+
+                # Download from remote
                 remote=https://raw.githubusercontent.com/StanfordAHA/aha/$BUILDKITE_BRANCH
-                echo curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
-                curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
-                source custom-checkout.sh
-                echo "--- FOO I am in dir `pwd`"
-                echo cp $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
-                cp $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
-                [ `docker images -q $IMAGE` ] || echo "--- (Re)creating garnet Image"
-                [ `docker images -q $IMAGE` ] || docker build --progress plain . -t "$IMAGE"
+                mkdir -p $COMMON
+                curl $$remote/.buildkite/bin/regress-metahooks.sh -o $REGRESS_METAHOOKS
             fi
-            REGRESSION_STEP=0 $REGRESS_METAHOOKS --pre-command
+
+            # If docker image is gone, e.g. in case of retry maybe, we'll have to rebuild it
+            (
+                # flock exclusionary zone ensures that only one guy builds the new image
+                lockfile=aha-flow-lock-$BUILDKITE_BUILD_NUMBER
+                i=1
+                while ! flock -n 9; do
+                    echo "Someone appears to be currently (re)building docker image"
+                    echo "Waited $((i++)) minutes so far..."
+                done
+                if ! `docker images -q $IMAGE`; then
+                    echo "CANNOT FIND DOCKER IMAGE '$IMAGE'"
+                    echo "And I have the lock so...guess I am the one who will be (re)building it"
+
+                    # Download and source custom-checkout script
+                    remote=https://raw.githubusercontent.com/StanfordAHA/aha/$BUILDKITE_BRANCH
+                    echo curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
+                    curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
+
+                    # Check out repo with latest Docker-build collateral...
+                    source custom-checkout.sh
+
+                    # echo "--- FOO I am in dir `pwd`"
+                    # echo cp $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
+                    # cp $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
+
+                    echo "--- (Re)creating garnet Image"
+                    docker build --progress plain . -t "$IMAGE"
+                else
+                    echo Okay looks likw someone else successfully built the missing docker image hooray
+                fi
+             ) 9>/tmp/aha-flow-lock-$BUILDKITE_BUILD_NUMBER
+             REGRESSION_STEP=0 $REGRESS_METAHOOKS --pre-command
+
         pre-exit:    $REGRESS_METAHOOKS --pre-exit
 
   command: REGRESSION_STEP=0 $REGRESS_METAHOOKS --commands
