Test of outcomes

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -5,14 +5,11 @@ env:
   # Default config is "pr_aha"
   CONFIG: ${CONFIG:-pr_aha}
 
-  # NSTEPS: "0 1 2 3 4 5 6 7 8 9"   # "Fast" plus nine regression steps
-  # NSTEPS: "4 5"
-  # NSTEPS: ""  # Gold check only (maybe?)
-  NSTEPS: "0 1 3 4 5"  # Numerical steps
-
-  # Fixme does not need to be env var. and also maybe nsteps as well
   # RSTEPS: (build gold 0 1 2 3 4 5 6 7 8 9)
-  RSTEPS: "build gold $$NSTEPS"  # Named steps (ish)
+  #   "build" creates two steps 'kprep' and 'r8prep', see regression-steps.sh
+  #   "gold" creates step "zircon_gold"
+  #   "0..9" creates steps "regress0".."regress9" see?
+  RSTEPS: "build gold 0 1 3"  # Named steps (ish)
 
   MAX_AGENTS: 4  # How many agents do we get to use for regression steps?
 
@@ -107,36 +104,45 @@ steps:
     - uber-workflow/run-without-clone:
 
   command: |
+      echo '- Use FAIL to summarize overall result'
+      FAIL=
 
-    echo '- Show outcomes from gold step(s)'
-    echo docker_gold outcome: `buildkite-agent step get "outcome" --step "docker_gold"`
-    echo zircon_gold outcome: `buildkite-agent step get "outcome" --step "zircon_gold"`
-    
-    echo '- Show outcomes from each regression step'
-    echo fast outcome:     `buildkite-agent step get "outcome" --step "regress0"`
-    for i in $$NSTEPS; do
-        echo regress$$i outcome: `buildkite-agent step get "outcome" --step "regress$$i"`
-    done
+      # "build" creates two steps 'kprep' and 'r8prep', see regression-steps.sh
+      if (echo "$$RSTEP" | grep build > /dev/null); then
+          echo '- Show outcomes from build steps'
+          echo khaki-build outcome: `buildkite-agent step get "outcome" --step "kprep"`
+          echo r8cad-build outcome: `buildkite-agent step get "outcome" --step "r8prep"`
+          [ $(buildkite-agent step get "outcome" --step "kprep")  == "passed" ] || FAIL=True
+          [ $(buildkite-agent step get "outcome" --step "r8prep") == "passed" ] || FAIL=True
+      fi
 
-    echo '- Use FAIL to summarize overall result'
-    FAIL=
-    [ $(buildkite-agent step get "outcome" --step "docker_gold") == "passed" ] || FAIL=True
-    [ $(buildkite-agent step get "outcome" --step "zircon_gold") == "passed" ] || FAIL=True
-    for i in $$NSTEPS; do
-        [ $(buildkite-agent step get "outcome" --step "regress$$i") == "passed" ] || FAIL=True
-    done
-    echo '-- FAIL=$$FAIL'
+      #"gold" creates step "zircon_gold"
+      if (echo "$$RSTEP" | grep gold > /dev/null); then
+          echo '- Show outcomes from gold step(s)'
+          echo zircon_gold outcome: `buildkite-agent step get "outcome" --step "zircon_gold"`
+          [ $(buildkite-agent step get "outcome" --step "zircon_gold") == "passed" ] || FAIL=True
+      fi
 
-    echo '- Send summary outcome "success" or "failure" to github PR'
-    # Note, /home/buildkite-agent/bin/status-update must exist on agent machine
-    # Also see ~steveri/bin/status-update on kiwi
-    [ "$$FAIL" ] && ~/bin/status-update --force failure || ~/bin/status-update --force success
+      # 0..9 creates steps "regress0".."regress9" see?
+      echo '- Show outcomes from each regression step'
+      for i in $$RSTEPS; do
+          if [ "$i" == 0 ]; then
+             echo fast outcome:     `buildkite-agent step get "outcome" --step "regress0"`
+             [ $(buildkite-agent step get "outcome" --step "regress0") == "passed" ] || FAIL=True
+             continue
+          fi
+          if (echo "$$i" | egrep '^[1-9]$' > /dev/null); then
+              echo regress$$i outcome: `buildkite-agent step get "outcome" --step "regress$$i"`
+              [ $(buildkite-agent step get "outcome" --step "regress$$i") == "passed" ] || FAIL=True
+          fi
+      done
 
-    echo '- Clean up your mess'
-    test -e $REGRESS_METAHOOKS && rm $REGRESS_METAHOOKS || echo okay
+      echo '-- FAIL=$$FAIL'
 
-    # No don't do this. Excludes ability to rerun etc.
-    # Also, COMMON is generally not very big.
-    # ~Also, code above will eliminate DELETEME files older than one week.~ (I don't think so...?)
-    # test -d $COMMON && rmdir $COMMON || echo okay
-    # /bin/rm -f /var/lib/buildkite-agent/builds/DELETEME/env-$BUILDKITE_BUILD_NUMBER
+      echo '- Send summary outcome "success" or "failure" to github PR'
+      # Note, /home/buildkite-agent/bin/status-update must exist on agent machine
+      # Also see ~steveri/bin/status-update on kiwi
+      [ "$$FAIL" ] && ~/bin/status-update --force failure || ~/bin/status-update --force success
+
+      echo '- Clean up your mess'
+      test -e $REGRESS_METAHOOKS && rm $REGRESS_METAHOOKS || echo okay
