iterating again, weird problem here iv (single vs. dbl quotes)

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -137,3 +137,18 @@ steps:
         fi
     done
 
+    # good to HERE maybe
+
+    echo "-- FAIL=$$FAIL"
+
+    # Note, /home/buildkite-agent/bin/status-update must exist on agent machine(s)
+    # Also see ~steveri/bin/status-update on kiwi
+    echo "- Send summary outcome 'success' or 'failure' to github PR"
+    if [ "$$FAIL" ]; then
+        ~/bin/status-update --force failure
+    else
+        ~/bin/status-update --force success
+    fi
+
+    echo '- Clean up your mess'
+    test -e "$$REGRESS_METAHOOKS" && rm "$$REGRESS_METAHOOKS" || echo okay
