cleanup

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -17,61 +17,52 @@ env:
       echo foo
       echo bar
 
-  PRE_COMMAND: |
-            # To test retry: FAIL first time through only
-            if [ "$$BUILDKITE_RETRY_COUNT" == "0" ]; then echo '--- FAIL b/c retry count is 0'; exit 13; fi
+  # This script allows retries even after original collateral is gone...
+  REGRESS_PRE_COMM: |
 
-            # Must restore in case of retries
-            echo 1 I am in dir `pwd`
-            if ! test -f $REGRESS_METAHOOKS; then
-                set -x
+      echo "--- REGRESS_PRE_COMMAND FOR STEP $$RPCSTEP"
 
-                # Download from remote
-                remote=https://raw.githubusercontent.com/StanfordAHA/aha/$BUILDKITE_BRANCH
-                mkdir -p $COMMON
-                curl $$remote/.buildkite/bin/regress-metahooks.sh -o $REGRESS_METAHOOKS
-                chmod +x $REGRESS_METAHOOKS
-            fi
-            echo 2 I am in dir `pwd`
+      # To test retry: FAIL first time through only
+      if [ "$$BUILDKITE_RETRY_COUNT" == "0" ]; then echo '--- FAIL b/c retry count is 0'; exit 13; fi
 
-            # If docker image is gone, e.g. in case of retry maybe, we'll have to rebuild it
-            (
-                set -x
-                # flock exclusionary zone ensures that only one guy builds the new image
-                lockfile=aha-flow-lock-$BUILDKITE_BUILD_NUMBER
-                i=1; while ! flock -n 9; do
-                    echo "Someone appears to be currently (re)building docker image"
-                    echo "Waited $((i++)) minutes so far..."
-                done
+      remote=https://raw.githubusercontent.com/StanfordAHA/aha/$BUILDKITE_BRANCH
 
-                echo "# We have the lock; look for $IMAGE"
-                if ! [ `docker images -q $IMAGE` ]; then
-                    echo "CANNOT FIND DOCKER IMAGE '$IMAGE'"
-                    echo "And I have the lock so...guess I am the one who will be (re)building it"
+      # In case of retry, may need to (re)download metahooks script
+      if ! test -f $REGRESS_METAHOOKS; then
+          mkdir -p $COMMON  # Make sure there is a landing pad for the downloaded file
+          echo curl $$remote/.buildkite/bin/regress-metahooks.sh -o $REGRESS_METAHOOKS
+          curl $$remote/.buildkite/bin/regress-metahooks.sh -o $REGRESS_METAHOOKS
+          chmod +x $REGRESS_METAHOOKS
+      fi
 
-                    # Download and source custom-checkout script
-                    remote=https://raw.githubusercontent.com/StanfordAHA/aha/$BUILDKITE_BRANCH
-                    echo curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
-                    curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
+      # If docker image is gone, e.g. in case of retry maybe, we'll have to rebuild it
+      (
+          # "flock" exclusionary zone ensures that only one guy builds the new image
+          lockfile=aha-flow-lock-$BUILDKITE_BUILD_NUMBER
+          i=1; while ! flock -n 9; do
+              echo "Someone appears to be currently (re)building docker image"
+              echo "Waited $((i++)) minutes so far..."
+          done
 
-                    # Check out repo with latest Docker-build collateral...
-                    source custom-checkout.sh
+          echo "# We have the lock; look for $IMAGE"
+          if ! [ `docker images -q $IMAGE` ]; then
+              echo "CANNOT FIND DOCKER IMAGE '$IMAGE'"
+              echo "And I have the lock so...guess I am the one who will be (re)building it"
 
-                    # echo "--- FOO I am in dir `pwd`"
-                    # echo cp $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
-                    # cp $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
+              echo "# Download and source custom-checkout script to get latest repo"
+              echo curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
+              curl $$remote/.buildkite/bin/custom-checkout.sh -o custom-checkout.sh
+              source custom-checkout.sh
 
-                    echo "--- (Re)creating garnet Image"
-                    docker build --progress plain . -t "$IMAGE"
-                else
-                    echo Docker image exists, hooray
-                fi
-            ) 9>/tmp/aha-flow-lock-$BUILDKITE_BUILD_NUMBER
-            echo 3 I am in dir `pwd`  # builds/<agent>/stanford-aha/aha-flow
-            pwd; cd .; # cd; pwd  # Get to a safe place maybe?
-            REGRESSION_STEP=0 $REGRESS_METAHOOKS --pre-command
-
-
+              echo "--- (Re)creating garnet Image"
+              docker build --progress plain . -t "$IMAGE"
+          else
+              echo Docker image exists, hooray
+          fi
+      ) 9>/tmp/aha-flow-lock-$BUILDKITE_BUILD_NUMBER
+      echo I am in dir `pwd`  # builds/<agent>/stanford-aha/aha-flow
+      cd .  # Got weird error without this...??
+      REGRESSION_STEP=$$RPCSTEP $REGRESS_METAHOOKS --pre-command
 
 steps:
 
@@ -279,7 +270,7 @@ steps:
     - uber-workflow/run-without-clone:
 
     - improbable-eng/metahook:
-        pre-command: $PRE_COMMAND
+        pre-command: RPCSTEP=0; $REGRESS_PRE_COMM
         pre-exit:    $REGRESS_METAHOOKS --pre-exit
 
   command: REGRESSION_STEP=0 $REGRESS_METAHOOKS --commands
