things be gettin cray

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -207,20 +207,25 @@ steps:
             echo "+++ RM_SRC1=$RM_SRC1 (me)"
             echo I am in dir `pwd`
             foo=bart
-            echo foo=$foo=$$foo
+            echo foo=$foo=$$foo  # /var/lib/buildkite-agent/builds/r8cad-docker-3/stanford-aha/aha-flow
             # echo "+++ RM_SRC2=$RM_SRC2 (docker step)"
             set -x
             # test -f $REGRESS_METAHOOKS || cp $$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin/regress-metahooks.sh $$COMMON
             # Must restore in case of retries
+            # test -f $REGRESS_METAHOOKS || echo "--- OOPS missing metahooks: cp $RM_SRC1 $REGRESS_METAHOOKS"
+            # test -f $REGRESS_METAHOOKS || cp $RM_SRC1 $REGRESS_METAHOOKS
             if ! test -f $REGRESS_METAHOOKS; then
-                /bin/rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH
-                git clone https://github.com/StanfordAHA/aha $BUILDKITE_BUILD_CHECKOUT_PATH
+                cd ..  # "/var/lib/buildkite-agent/builds/r8cad-docker-3/stanford-aha" maybe
+                aha_clone=$BUILDKITE_BUILD_CHECKOUT_PATH;
+                /bin/rm -rf $$aha_clone; mkdir -p $$aha_clone
+                git clone https://github.com/StanfordAHA/aha $$aha_clone; cd $$aha_clone;
+                # git remote set-url origin https://github.com/StanfordAHA/aha     # Why?
+                # git clean -ffxdq
+                # set +x
+                # bin=$BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/bin
+                # source $$bin/custom-checkout.sh
+                cp .buildkite/bin/regress-metahooks.sh $REGRESS_METAHOOKS
             fi
-
-
-
-            test -f $REGRESS_METAHOOKS || echo "--- OOPS missing metahooks: cp $RM_SRC1 $REGRESS_METAHOOKS"
-            test -f $REGRESS_METAHOOKS || cp $RM_SRC1 $REGRESS_METAHOOKS
             REGRESSION_STEP=0 $REGRESS_METAHOOKS --pre-command
         pre-exit:    $REGRESS_METAHOOKS --pre-exit
 
