Ci cleanup (#1934)
* updated comments
* fix a little bug; clones repo in case it was never done yet before
* prep for offloading aha-submod-flow steps
* cannot clone already-cloned dir
* missed a trick, need empty dir before clone...
* merge aha-flow-steps.sh into custom-checkout.sh maybe
* Reduce amount of debug info in log
* eliminate source of unnecessary error code
* heads or tails?
* buildkite-message experiment
* experiment failed
* trying to fix buildkite message
* restore original code, without debug printfs
* delete outmoded pipeline step files
* better status-update maybe
* struggling with dev branches and such
* bad square brackets. bad!
* Add a step to clean up temp files
* clean up comments and structure: regress-metahooks.sh
* clean up comments and structure: set-trigfrom-and-reqtype.sh
* clean up comments and structure: pipeline.yml

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -76,7 +76,7 @@ steps:
         # status-update exit status will tell us if this step has failed
         if ! ~/bin/status-update pending; then
             # Build failed already, remove the docker image and begone
-            (set -x; docker image rm "garnet:aha-flow-build-$${BUILDKITE_BUILD_NUMBER}" --no-prune)
+            (set -x; docker image rm "$$IMAGE" --no-prune) || echo okay
         fi
 
   commands:
@@ -163,6 +163,7 @@ steps:
 # STEP: onyx regression 1
 
 - label: "Regress 1"
+  key: "regress1"
   env: { CONTAINER: deleteme-regress1-$BUILDKITE_BUILD_NUMBER }
 
   plugins:
@@ -178,6 +179,7 @@ steps:
 # STEP: onyx regression 2
 
 - label: "Regress 2"
+  key: "regress2"
   env: { CONTAINER: deleteme-regress2-$BUILDKITE_BUILD_NUMBER }
 
   plugins:
@@ -192,6 +194,7 @@ steps:
 # STEP: onyx regression 3
 
 - label: "Regress 3"
+  key: "regress3"
   env: { CONTAINER: deleteme-regress3-$BUILDKITE_BUILD_NUMBER }
 
   plugins:
@@ -201,3 +204,36 @@ steps:
         pre-exit:    $REGRESS_METAHOOKS --pre-exit
 
   command: REGRESSION_STEP=3 $REGRESS_METAHOOKS --commands
+
+########################################################################
+# STEP: Cleanup
+
+# Wait for all steps to complete before sending out final status
+# This step should run regardless of whether prev steps failed
+- wait: { continue_on_failure: true } 
+
+- label: "Cleanup"
+  command: |
+
+    echo '- Show outcomes from each regression step'
+    echo regress1 outcome: `buildkite-agent step get "outcome" --step "regress1"`
+    echo regress2 outcome: `buildkite-agent step get "outcome" --step "regress2"`
+    echo regress3 outcome: `buildkite-agent step get "outcome" --step "regress3"`
+
+    echo '- Use FAIL to summarize overall result'
+    FAIL=
+    set -x
+    [ $(buildkite-agent step get "outcome" --step "regress1") == "passed" ] || FAIL=True
+    [ $(buildkite-agent step get "outcome" --step "regress2") == "passed" ] || FAIL=True
+    [ $(buildkite-agent step get "outcome" --step "regress3") == "passed" ] || FAIL=True
+    echo '-- FAIL=$$FAIL'
+
+    echo '- Send summary outcome "success" or "failure" to github PR'
+    # Note, /home/buildkite-agent/bin/status-update must exist on agent machine
+    # Also see ~steveri/bin/status-update on kiwi
+    [ "$$FAIL" ] && ~/bin/status-update --force failure || ~/bin/status-update --force success
+
+    echo '- Clean up your mess'
+    test -e $REGRESS_METAHOOKS && rm $REGRESS_METAHOOKS || echo okay
+    test -d $COMMON && rmdir $COMMON || echo okay
+    /bin/rm -f /var/lib/buildkite-agent/builds/DELETEME/env-$BUILDKITE_BUILD_NUMBER
