fails successfully; hopefully will PASS once michaels changes go through...

diff --git a/aha/bin/app b/aha/bin/app
--- a/aha/bin/app
+++ b/aha/bin/app
@@ -17,6 +17,7 @@ HELP="
     $bn <width>x<height> <app> [ OPTIONAL-FLAGS ]
     $bn --list-suites          # Tell names of regression suites e.g. 'fast', 'pr_aha' etc.
     $bn --show-suite <suite>   # Show contents of specified suite
+    $bn --run-suite <suite>    # RUN the specified suite
     $bn --show                 # Same as '--show-suite all'
 
   OPTIONAL FLAGS
@@ -36,6 +37,7 @@ HELP="
     $bn --verilator 8x8 apps/pointwise
 
   QUICK REFERENCE:
+    $bn --run-suite fast
     $bn --show-suite fast --zircon
     $bn --show-suite fast --nozircon
     $bn --show-suite full
@@ -55,6 +57,7 @@ app_flags="$@"
 DBG=
 SIM=vcs
 LIST_SUITES=
+RUN_SUITE=
 ZIRCON=True
 FCR=4; MU=8  # (fabric_)cols_removed, mu_oc_0 = 4, 8
 UPDATE_SRC=; UPDATE_DST=;
@@ -66,6 +69,7 @@ while [ $# -gt 0 ] ; do
         --show*)      
           if not_suite "$2"; then SUITE='all'; else SUITE="$2"; shift; fi ;;
 
+        --run*)        RUN_SUITE=$2; shift ;;
         --*remove*)    FCR=$2;       shift ;;
         --mu*)         MU=$2;        shift ;;
 
@@ -283,6 +287,24 @@ if ! [ "$IN_DOCKER" ]; then
         # set +x; # ENDGROUP
     fi
 
+    # Need sim_sram etc. SIXTY-NINE MEGABYTE verilog file from local machine :(
+    # - Generated by Kartik's Voyager tool I guess...might have proprietary stuff
+    #   maybe...therefore we squirrel it away in a private place :(
+    # 
+    # -rw-r--r-- 1 mcoduoza users  69M May 27 17:32 /nobackup/zircon/MatrixUnit_sim_sram.v
+    # -rw-r--r-- 1 mcoduoza users 409K May 27 17:33 /nobackup/zircon/MatrixUnitWrapper_sim.v
+
+    for f in MatrixUnit_sim_sram.v MatrixUnitWrapper_sim.v; do
+        if ! test -e /nobackup/zircon/$f; then
+            for i in {1..100}; do echo ERROR; done
+            echo 'ERROR cannot find $f in dir /nobackup/zircon/'
+            echo 'ERROR test will probably FAIL!'
+            echo 'Continuing on anyway...'
+        else
+            docker cp /nobackup/zircon/$f $container:/aha/garnet/$f
+        fi
+    done
+
     # For debugging; copy latest script in dev to container
     if [ "$COPY_SCRIPT" ]; then
         echo "DEBUGGING: Copy contents of '$0' over as '/aha/aha/bin/app'"
@@ -372,6 +394,10 @@ fi
 # Clean up from possible previous run(s) e.g. in case of CONTAINER_REUSE
 # (which no longer exists maybe) and/or maybe just plain old paranoia...
 (cd /aha/garnet; make clean)
+
+########################################################################
+# Haha if RUN_SUITE is set just ignore everything that happened up there haha
+[ "$RUN_SUITE" ] && config=$RUN_SUITE
 
 ########################################################################
 # Finally: run it!!
